title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!

remote_theme: just-the-docs/just-the-docs

url: https://just-the-docs.github.io


logo: "/assets/images/logo.png"
color_scheme: dark